#ifndef _BUTTON_H_
#define _BUTTON_H_

#include "common.h"

enum BUTTON_STATE{
	BUTTON_STATE_INIT,
  BUTTON_STATE_CLICK,
  BUTTON_STATE_CLICK_ACT,
  BUTTON_STATE_DOUBLE_CLICK,
  BUTTON_STATE_DOUBLE_CLICK_ACT,
  BUTTON_STATE_PRESSED_1S,
	BUTTON_STATE_PRESSED_1S_ACT,
  BUTTON_STATE_PRESSED_3S,
  BUTTON_STATE_PRESSED_3S_ACT,
  BUTTON_STATE_PRESSED_5S,
  BUTTON_STATE_PRESSED_5S_ACT,
  BUTTON_STATE_NONE
};

enum BUTTON_NAME{
  BUTTON_NAME_MENU,
  BUTTON_NAME_UP,
  BUTTON_NAME_DOWN,
  BUTTON_NAME_POWER,
  BUTTON_NAME_CAL
};

int is_button_pressed(void);
u8 get_button_state(u8 button);
void set_button_state(u8 button, u8 state);

#endif
